version: '3.6'
services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - minio
      - front-end
    env_file:
      - .env
    environment:
      DB_DATASOURCE_USER: ${DB_USERNAME}
      DB_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      DB_DATASOURCE_URL: ${DB_URL}
    networks:
      - cloud-file
    ports:
      - "8080:8080"

  postgres:
    image: postgres:17.5
    restart: always
    container_name: postgres-container
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - cloud-file

  front-end:
    image: front-end:13.0
    ports:
      - "80:80"

  minio:
    image: quay.io/minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_USERNAME}
      MINIO_ROOT_PASSWORD: ${MINIO_PASSWORD}
    volumes:
      - ./minio-data:/data
    command: server /data --console-address ":9001"
    networks:
      - cloud-file

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data


volumes:
  redis_data:
  pgdata:

networks:
  cloud-file:
    driver: bridge
    name: cloud-file

